version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27018:27017"
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: library_api
      MYSQL_USER: root
      MYSQL_PASSWORD: MyNewPass5!
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: flask_container
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_HOST: localhost
      DATABASE_USER: root
      DATABASE_PASSWORD: MyNewPass5!
      DATABASE_NAME: library_api

volumes:
  db_data: