version: '3.0'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
    volumes:
      -library-data:/var/lib/mysql/data
    networks:
      - flask-network

  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      -library-data:/data/db
    networks:
      - flask-network

  flask-app:
    image: library-app:1.0
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:rootpassword@mysql-db:3306/dbname
      - MONGO_URI=mongodb://mongo-db:27017/
    depends_on:
      - mysql
      - mongodb
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge

volumes:
  library-data:
    driver: local

