version: '3.0'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
      - "3306:3306"
      - "27017:27017"
    networks:
      - flask-network
    volumes:
      - "/home/aishni.narain@intelegencia.com/Desktop/Library System Api/Library-Management-System-Api:/app"
      - mysql-data:/var/lib/mysql
      - mongo-data:/data/db
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf

volumes:
  mysql-data:
    driver: local
  mongo-data:
    driver: local

networks:
  flask-network:
    driver: bridge