"""empty message

Revision ID: b2fb747d435b
Revises: c82596bde184
Create Date: 2024-03-22 12:32:41.643310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fb747d435b'
down_revision = 'c82596bde184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_return_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_books', schema=None) as batch_op:
        batch_op.drop_column('expected_return_date')

    # ### end Alembic commands ###
